=== saidaHF/webs_clase/UF1/XML/practica_validacio/personas.dtd
<!ELEMENT personas (persona+)>
<!ELEMENT persona (nombre, nacimiento, direccion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nacimiento (#PCDATA)>
<!ELEMENT direccion (calle, poblacion, provincia, cpostal, varios)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT cpostal (#PCDATA)>
<!ELEMENT varios EMPTY>

=== saidaHF/webs_clase/UF1/XML/practica_validacio/personas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personas SYSTEM "personas.dtd">
<personas>
      <persona>
            <nombre>Jonh Smith</nombre>
            <nacimiento>21 de Enero de 1969</nacimiento>
            <direccion>
              <calle>Avda.Universidad,30</calle>
              <poblacion>Leganés</poblacion>
              <provincia>Madrid</provincia>
              <cpostal>08191</cpostal>
              <varios/>
            </direccion>
      </persona>
</personas>
