=== saidaHF/webs_clase/UF1/XSD/E2_4_xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
     <xsd:element name="raiz">
         <xsd:complexType>
             <xsd:sequence>

<xsd:element name="desordenParcial">
<xsd:complexType>
<xsd:sequence>
<xsd:element name="elementoOpcion1SimpleVacio"><xsd:complexType/></xsd:element>
<xsd:choice>
<xsd:element name="elementoOpcion2aSimpleVacio"><xsd:complexType/></xsd:element>
<xsd:element name="elementoOpcion2bSimpleVacio"><xsd:complexType/></xsd:element>
</xsd:choice>
<xsd:element name="elementoOpcion3SimpleVacio"><xsd:complexType/></xsd:element>
<xsd:element name="elementoOpcion4SimpleVacio"><xsd:complexType/></xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>

<xsd:element name="desordenTotalUnaOcurrencia">
<xsd:complexType>
<xsd:all>
<xsd:element name="elementoDesordenado1Simple" type="xsd:integer"/>
<xsd:element name="elementoDesordenado2Simple" type="xsd:integer"/>
<xsd:element name="elementoDesordenado3Simple" type="xsd:integer"/>
<xsd:element name="elementoDesordenado4Simple" type="xsd:integer"/>
</xsd:all>
</xsd:complexType>
</xsd:element>

<xsd:element name="desordenTotalMultiplesOcurrencias">
<xsd:complexType>
<xsd:choice maxOccurs="unbounded">

<xsd:element name="elementoDesordenado1Vacio">
<xsd:complexType>
<xsd:attribute name="atributo1" type="xsd:string"/>
</xsd:complexType>
</xsd:element>

<xsd:element name="elementoDesordenado2Contenido">
<xsd:complexType>
<xsd:simpleContent>
<xsd:extension base="xsd:integer">
<xsd:attribute name="atributo2" type="xsd:string"/>
</xsd:extension>
</xsd:simpleContent>
</xsd:complexType>
</xsd:element>

<xsd:element name="elementoDesordenado3Complejo">
<xsd:complexType>
<xsd:sequence>
<xsd:element name="elementoOrdenado1Simple" type="xsd:integer"/>
<xsd:element name="elementoOrdenado2Simple" type="xsd:integer"/>
<xsd:element name="elementoOrdenado3Simple" type="xsd:integer"/>
<xsd:element name="elementoOrdenado4Simple" type="xsd:integer"/>
</xsd:sequence>
<xsd:attribute name="atributo3" type="xsd:string"/>
</xsd:complexType>
</xsd:element>

</xsd:choice>
</xsd:complexType>
</xsd:element>


             </xsd:sequence>
         </xsd:complexType>
     </xsd:element>
</xsd:schema>

=== saidaHF/webs_clase/UF1/XSD/E2_4_xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<raiz xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="E2_4_xsd.xsd">
   <desordenParcial>
     <elementoOpcion1SimpleVacio/>
     <elementoOpcion2bSimpleVacio/>
     <elementoOpcion3SimpleVacio/>
     <elementoOpcion4SimpleVacio/>
   </desordenParcial>
   <desordenTotalUnaOcurrencia>
     <elementoDesordenado3Simple>3</elementoDesordenado3Simple>
     <elementoDesordenado1Simple>1</elementoDesordenado1Simple>
     <elementoDesordenado2Simple>2</elementoDesordenado2Simple>
     <elementoDesordenado4Simple>4</elementoDesordenado4Simple>
   </desordenTotalUnaOcurrencia>
   <desordenTotalMultiplesOcurrencias>
     <elementoDesordenado1Vacio atributo1="a"></elementoDesordenado1Vacio>
     <elementoDesordenado2Contenido atributo2="b">1</elementoDesordenado2Contenido>
     <elementoDesordenado1Vacio atributo1="c"></elementoDesordenado1Vacio>
     <elementoDesordenado1Vacio atributo1="d"></elementoDesordenado1Vacio>
     <elementoDesordenado2Contenido atributo2="e">2</elementoDesordenado2Contenido>
     <elementoDesordenado2Contenido atributo2="f">3</elementoDesordenado2Contenido>
     <elementoDesordenado3Complejo atributo3="g">
       <elementoOrdenado1Simple>1</elementoOrdenado1Simple>
       <elementoOrdenado2Simple>2</elementoOrdenado2Simple>
       <elementoOrdenado3Simple>3</elementoOrdenado3Simple>
       <elementoOrdenado4Simple>4</elementoOrdenado4Simple>
     </elementoDesordenado3Complejo>
     <elementoDesordenado2Contenido atributo2="h">4</elementoDesordenado2Contenido>
     <elementoDesordenado2Contenido atributo2="i">5</elementoDesordenado2Contenido>
   </desordenTotalMultiplesOcurrencias>
</raiz>
