=== saidaHF/webs_clase/UF1/practica XML XSD/socis.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
            <xs:element name="socis">
                    <xs:complexType>
                            <xs:sequence>
                                    <xs:element name="soci" minOccurs="1" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                   <xs:element name="nom" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                                   <xs:element name="cognom" type="xs:string" minOccurs="0" maxOccurs="2"/>
                                                   <xs:element name="edat" minOccurs="0" >
                                                     <xs:simpleType>
                                                          <xs:restriction base="xs:integer">
                                                              <xs:minInclusive value="18"/> 
                                                          </xs:restriction>
                                                     </xs:simpleType>
                                                     </xs:element>
                                                   <xs:element name="DNI" type="xs:string" minOccurs="0" maxOccurs="1"/>
                                                   <xs:element name="dataNaixement" type="xs:date" minOccurs="0" maxOccurs="1"/>     
                                                   <xs:element name="ciutat" type="xs:string"/> 
                                                   <xs:element name="posicioRanking" type="xs:float" minOccurs="0" maxOccurs="10"/> 
                                            </xs:sequence>
                                            <xs:attribute name="id" type="xs:string" use="required"/>
                                        </xs:complexType>
                            </xs:element>
                            </xs:sequence>
                    </xs:complexType>
            </xs:element>
</xs:schema>

=== saidaHF/webs_clase/UF1/practica XML XSD/socis.xml
<?xml version="1.0" encoding="UTF-8"?>
<socis xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="socis.xsd">  
        <soci id="num13">
                 <nom>Andreu</nom>
                 <cognom>Garcia</cognom>
                 <edat>30</edat>
                 <DNI>56565656X</DNI>
                 <dataNaixement>1990-03-07</dataNaixement>  <!-- fecha es año mes dia-->
                 <ciutat>Rubí</ciutat>
                 <posicioRanking>8.5</posicioRanking> <!-- decimales con punto, coma NO-->
         </soci>
         <soci id="num27">
                 <nom>Anna</nom>
                 <cognom>Casal</cognom>
                 <edat>22</edat>
                 <DNI>98989898L</DNI>
                 <dataNaixement>1998-06-15</dataNaixement>
                 <ciutat>Sabadell</ciutat>
                 <posicioRanking>9.8</posicioRanking>
         </soci>
</socis>
